---
title: "Data science tutorials"
description: Data preprocessing and wrangling, tutorials, statistical analyses, modeling, and so on
date: Jan 12, 2019
author:
    - name: Hause Lin
      url: https://www.hauselin.com
      affiliation: University of Toronto
      affiliation_url: https://www.utoronto.ca/
citation_url: https://hausetutorials.netlify.com/
slug: lin2019rdatascience
site: radix::radix_website
---

<script data-ad-client="ca-pub-4491293927954947" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

## What is this site about? 

This site contains introduction tutorials as well as relatively advanced data analysis tips/tricks I have used to analyze data. Occasionally, I'll also explain statistical procedures and concepts with code. I have used these tutorials and articles to teach data science in graduate school. In my tutorials and articles, I usually try my best to explain *how* things work.

* tutorials: beginner R tutorials ([R programming basics](0001_rbasics.html), [tidyverse, data.table](0002_tidyverse_datatable.html), etc.)
* [articles](articles.html): more advanced analysis tricks/tips and statistical concepts illustrated with code

If you want to learn more about who I am, [visit my personal site](https://www.hauselin.com).

## Consider being a patron and supporting my work?

[Donate and become a patron](https://donorbox.org/support-my-teaching): If you find value in what I do and have learned something from my site, please consider becoming a patron. It takes me many hours to research, learn, and put together tutorials. Your support really matters.

## Where to begin?

If you're new to R, start with the tutorials. If you're looking for tips/tricks to improve your existing R workflow or explanations of statistical concepts, check out my [articles](articles.html).

## Questions or want to get in touch?

If you have any questions or comments, [email me](mailto:hauselin@gmail.com) or create a new issue [here](https://github.com/hauselin/rtutorialsite/issues) or follow me on [Twitter](https://twitter.com/hauselin). 

## More resources?

* [DataCamp](http://datacamp.com/): mostly R and Python tutorials
* my [hausekeep R package](https://hauselin.github.io/hausekeep/): contains functions for experimental psychological research
* [tidyverse](https://www.tidyverse.org/): contains many packages (e.g., dplyr, tidyr, ggplot2, stringr)
    * manipulate dataframes (and tibbles) easily with tidyr, dplyr; make beautiful plots with clean syntax (ggplot2)
* [data.table](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html)
    * powerful, extremely fast, and simple way to manipulate dataframes/datatables
