---
title: "random walks"
description: "A short description of the post."
author:
  - name: Hause Lin
    url: {}
date: 02-23-2019
draft: true
output:
  radix::radix_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## What is a random walk? 


## 1-dimensional walk

```{r}
possibleMoves <- c(-1, 1) # left right movement (-1, 1)
steps <- 1e1
eachStep <- sample(x = possibleMoves, size = steps, replace = T, prob = c(.5, .5))
eachStep

distance <- sum(eachStep)
distance
mean(distance)
plot(distance)

```


```{r}
possibleMoves <- c(-1, 1) # left right movement (-1, 1)
steps <- 1e2
experiments <- 1e3
mat1 <- matrix(unlist(lapply(1:experiments, function(x) 
  sample(x = possibleMoves, size = steps, replace = T, prob = c(.5, .5)))), 
  nrow = experiments, ncol = steps, byrow = T)
mat1

mean(rowSums(mat1))
mean(colSums(mat1))

```


```{r}
possibleMoves <- c(-1, 1) # left right movement (-1, 1)
steps <- 1e1
eachStep <- sample(x = possibleMoves, size = steps, replace = T, prob = c(.5, .5))
eachStep

sum(eachStep)^2
```




```{r}

```

